# Generated by Django 3.2.6 on 2021-11-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_comment',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Blog_Comment',
        ),
    ]
